### PR TITLE
Update readmes with configlet

### PR DESCRIPTION
**Pull request by cmcaine**

### CODE REVIEW

**Review by SaschaMann — APPROVED** [review]
Thanks :)

**Comment by cmcaine** [comment]
Huh, I'm surprised the notebook checks passed.

**Comment by SaschaMann** [comment]
Hm, weird. I checked that the README was updated already (it was) so I figured it passed due to that.

[Build log](https://github.com/exercism/julia/runs/1271520477?check_suite_focus=true):
```
[ Info: Generating notebooks...
ERROR: LoadError: SystemError: opening file "/home/runner/work/julia/julia/bin/../exercises/reverse-string/reverse-string.jl": No such file or directory
Stacktrace:
 [1] systemerror(::String, ::Int32; extrainfo::Nothing) at ./error.jl:168
 [2] #systemerror#48 at ./error.jl:167 [inlined]
 [3] systemerror at ./error.jl:167 [inlined]
 [4] open(::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing) at ./iostream.jl:284
 [5] open at ./iostream.jl:273 [inlined]
 [6] open(::Base.var"#308#309"{Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}}, ::String; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./io.jl:323
 [7] open at ./io.jl:323 [inlined]
 [8] #readlines#307 at ./io.jl:523 [inlined]
 [9] readlines at ./io.jl:523 [inlined]
 [10] generate_notebook(::String) at /home/runner/work/julia/julia/bin/generate-notebooks.jl:12
 [11] generate_notebooks() at /home/runner/work/julia/julia/bin/generate-notebooks.jl:110
 [12] top-level scope at /home/runner/work/julia/julia/bin/generate-notebooks.jl:115
 [13] include(::Function, ::Module, ::String) at ./Base.jl:380
 [14] include(::Module, ::String) at ./Base.jl:368
 [15] exec_options(::Base.JLOptions) at ./client.jl:296
 [16] _start() at ./client.jl:506
in expression starting at /home/runner/work/julia/julia/bin/generate-notebooks.jl:115
```

The check errored but somehow CI passed...?

**Comment by SaschaMann** [comment]
I think #276 should fix that.

**Pull request merged**
