### PR TITLE
Fix exercise README template

### PR DESCRIPTION
**Pull request by Teo-ShaoWei**
Refers to #161.

Update `config/exercise_readme.go.tmpl` to add in the missing newline in the generated README before `## Source`, and remove the extra newline after that block. The new template ensure that the generated README have consistent single newline in the event of missing `.Hints`, `.TrackInsert`, and/or `.Spec.Credits`.

Most READMEs will manually cater for it after generation, but that will make `bin/configlet generate .` be non-idempotent.

Also update READMEs that didn't cater for the missing/additional newline.

### CODE REVIEW

**Comment by Teo-ShaoWei** [comment]
This is seriously delicate... I deem it to be the limitation of the templating language =P

**Comment by SaschaMann** [comment]
Thanks! I'm not familiar with the template language, so I'll have to trust you that it works as you outline it :D The output definitely looks better.

Could you run `julia bin/generate_notebooks.jl` to update the README embedded in the Jupyter notebooks, please?

**Comment by Teo-ShaoWei** [comment]
Ah I see, I guess that's why Travis CI complained. Ok, I've done the fixup as per your recommendation. Thanks much for the review!

**Comment by SaschaMann** [comment]
> I guess that's why Travis CI complained.

Yep. It's a bit hidden in the log if you don't know that the check exists.

**Pull request merged**
