### PR TITLE
Add check for denominator not being 0 in testsets

### PR DESCRIPTION
**Pull request by miguelraz**
This blew up in my face.
Here's the fix. 🦾

### CODE REVIEW

**Comment by miguelraz** [comment]
Note that we could a test that checks if `RationalNumber(1, 0) == Inf && RationalNumber(-1, 0) == -Inf` or something like that.

**Comment by SaschaMann** [comment]
> Note that we could a test that checks if `RationalNumber(1, 0) == Inf && RationalNumber(-1, 0) == -Inf` or something like that.

That's not Base's behaviour. `Rational(1, 0)` is a valid number:

```
julia> 1//0
1//0
```

**Comment by SaschaMann** [comment]
To stay consistent with Base, I think we should not skip these tests.

**Pull request closed without merging**
