### PR TITLE
Verbose Unit Testing Update

### PR DESCRIPTION
**Pull request by depial**
I've updated all the the `runtests.jl` files to use verbose unit testing similar to what is mentioned in [this issue](https://github.com/exercism/julia/issues/684). However, there are two slight modifications:
1. I've changed the `runtests.jl` files in all of the following folders: `exercises/concept`, `exercises/concept.wip`, `exercises/practice`, instead of just those in `exercises/practice`
2. I have made the description for the top level testset `"test"` in order to limit the impact on [what is printed in the test name on the website](https://github.com/exercism/julia/pull/680#issuecomment-1886500751), while still remaining informative for those who use the CLI.

The original description for the top level testset was the exercise name. However, this can be quite long (taking up a lot of space in the website test results), and is also rather irrelevant since the student presumably already knows what exercise they are doing. `tests` is shorter, standardized and informative on the CLI since it corresponds to a summary of all test outcomes (as shown below).

image

### CODE REVIEW

**Comment by depial** [comment]
Due to test failures, I also modified `concept.wip/encounters/runtests.jl` by moving the struct definitions outside the local scope of the `testset` wrapper. All tests are passing now.

**Comment by depial** [comment]
@ErikSchierboom I've had a look at the test runner and I think the fix to [remove the top-level category](https://github.com/exercism/julia/pull/680#issuecomment-1886500751) from the test name  on the website is fairly straightforward. I had standardized the top-level testset description for all the exercises in this PR as `tests` in order to minimize any effects of this not being fixed, but I could change the descriptions if desired. Let me know if there is a preference.

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom I've had a look at the test runner and I think the fix to https://github.com/exercism/julia/pull/680#issuecomment-1886500751 from the test name on the website is fairly straightforward. I had standardized the top-level testset description for all the exercises in this PR as tests in order to minimize any effects of this not being fixed, but I could change the descriptions if desired. Let me know if there is a preference.

I think I'm fine with the standardized description, as the context is indeed known. Before we merge this, could you add a test case with the new runtests.jl structure to https://github.com/exercism/julia-test-runner/tree/main/test/fixtures? The test runner should work well with both the old and the new format.

**Comment by depial** [comment]
I've tried to add a test case to the test-runner and to fix the test name issue. I opened a [PR](https://github.com/exercism/julia-test-runner/pull/111)(closed automatically by github-actions) that has both of these fixes.

**Review by ErikSchierboom — APPROVED** [review]
Thanks for the test runner PR!

**Comment by depial** [comment]
> Thanks for the test runner PR!

Cheers!

**Comment by depial** [comment]
I don't know why, since all the checks passed here earlier, but CI is now failing for `Julia 1.6 - macOS-latest`

image

**Comment by ErikSchierboom** [comment]
That's just the setup workflow, so likely just an intermittent error.

**Comment by ErikSchierboom** [comment]
It was not, but https://github.com/exercism/julia/pull/733 fixes it.

**Pull request merged**
