### PR TITLE
Fix JSON file formatting

### PR DESCRIPTION
**Pull request by colinleach**
This is purely the result of running `bin/configlet fmt -u -y`.

The changes are largely cosmetic. The most important thing is they remove the noise from `configlet fmt` output, which should now show any new problems without having to scroll through 79 old ones.

### CODE REVIEW

**Comment by depial** [comment]
> Should this be marked as `[no important files changed]`? That's something I've not dealt with before, and need to get my head around.

I suspect it doesn't need that. Here's a bit of the [docs](https://exercism.org/docs/building/tracks#h-maintenance) which gives some explanation, but in short the `[no important files changed]` seems to help "avoid triggering unnecessary test runs".

**Comment by colinleach** [comment]
@depial, do you have authority to approve this, or do we need a cross-track-maintainer?

**Review by depial — APPROVED** [review]
lgtm

**Comment by colinleach** [comment]
thanks!

**Comment by depial** [comment]
Cheers! 

If anything else is sufficiently reviewed that we can merge, you can feel free to let me know. I'm still not used to having merging powers, so I'm hesitant to use them

**Comment by colinleach** [comment]
> I'm still not used to having merging powers

I know the feeling!

**Comment by depial** [comment]
@colinleach I've just noticed that there seems to be two versions of the Leap exercise on the [website](https://exercism.org/tracks/julia/exercises). Can you see this too or is it something with my browser?

From what I can tell, they are clones, with the only difference I can see being the blurb (though I only made a cursory exploration). Even all of the solutions seem to be the same (at least I assume they are the same since they both have 69 pages of solutions and the same top solutions)

I can't see anything in the `.json` files that would be responsible for that, but I'm leaving the message here because this is my best guess as to what could have lead to it.

Comparative weirdness:
- On the [overview tab](https://exercism.org/tracks/julia) there is only one version and total exercise count is 95
- On the [practice tab](https://exercism.org/tracks/julia/exercises) there are two versions and total exercise count is 96

**Comment by colinleach** [comment]
This is a mess, not of our making.

If you look at it in an incognito window, everything is good. As maintainers, we're seeing a Leap clone because the previous maintainers wanted to use this as a Concept exercise. This is *strictly forbidden* by Jeremy, who insists on keeping Concept and Practice exercises totally separate. I hear rumors that there have been bad-tempered arguments about this in the past, which he refuses to repeat (and he's the CEO, so tends to have the last word).

The files are in [`exercises/concept.wip`](https://github.com/exercism/julia/tree/main/exercises/concept.wip/leap). My recommendation is to submit a PR to remove that duplicate Leap directory. Even if we somehow wanted to use it, we wouldn't be allowed. Rightly, IMHO.

**Comment by depial** [comment]
Now that you mention that, it reminds me of an open [PR #365](https://github.com/exercism/julia/pull/365). It looks like they planned to rename it and then deprecate it, but that was almost 3 1/2 years ago. I don't know how much of that process is still relevant (e.g. Do we have to deprecate something or can we simply remove it?). Also, the file mentioned in the PR, `exercises/concept/leap/`, is no longer there (presumably moved into `concept.wip`)

**Comment by colinleach** [comment]
Just deleting it should be OK.

**Comment by depial** [comment]
I'll try to take a look at doing that tomorrow. 

> Closing https://github.com/exercism/julia/pull/365 may also be a good idea.

I feel like there's quite a few old PRs that are probably able to be closed as obsolete, but I'm not sure if it's the norm to keep them around for some reason

**Pull request merged**
