### PR TITLE
Regenerate READMEs

### PR DESCRIPTION
**Pull request by cmcaine**
Replaces #164

### CODE REVIEW

**Comment by cmcaine** [comment]
Ah, I've found the issue. I can improve this.

**Comment by cmcaine** [comment]
dnd-character says that it's tested on versions of julia v1.1 and up, does it actually not work on Julia v1.0?

**Comment by cmcaine** [comment]
This is ready to go, imo :)

**Comment by SaschaMann** [comment]
> dnd-character says that it's tested on versions of julia v1.1 and up, does it actually not work on Julia v1.0?

It does, or CI wouldn't pass. The exercise was a GCI submission, maybe they hand-wrote the file, and it wasn't noticed during review.

**Comment by cmcaine** [comment]
Cool, that's what I thought. Fixed now.

**Pull request merged**
