### PR TITLE
Add new exercise 

### PR DESCRIPTION
**Pull request by Delta456**

### CODE REVIEW

**Comment by SaschaMann** [comment]
@Delta456 You abandoned the task on the Code-in site, do you want to continue working on this or not?

**Comment by Delta456** [comment]
I don't know how t.o do it correctly. I need help setting this up. Can you help me?

**Comment by SaschaMann** [comment]
Sure! The [Contributing Guide](https://github.com/exercism/julia/blob/master/CONTRIBUTING.md#implementing-existing-exercise) walks you through the process step by step, have you followed it? What specifically do you need help with?

**Comment by Delta456** [comment]
@SaschaMann Can you tell why my build is failing?

**Pull request closed without merging**
