### PR TITLE
raindrops: sync

### PR DESCRIPTION
**Pull request by ErikSchierboom**
Sync the `raindrops` exercise with the latest data, as defined in https://github.com/exercism/problem-specifications/tree/main/exercises/raindrops.

- Feel free to close this PR if there is another PR that also syncs this exercise.
- When approved, feel free to merge this PR yourselves (you don't have to wait for me).

As this PR only updates docs and/or metadata, it won't trigger a re-run of existing solutions (see [the docs](https://exercism.org/docs/building/tracks)).

### CODE REVIEW

**Comment by cmcaine** [comment]
These look like good changes, but can wait until #662 is merged to avoid extra merge conflicts in that PR.

**Comment by ErikSchierboom** [comment]
I'll convert to a draft then

**Comment by cmcaine** [comment]
If this is still relevant could you rebase it or whatever, please?

**Comment by ErikSchierboom** [comment]
@cmcaine Rebased!

**Review by cmcaine — APPROVED** [review]
Thanks!

**Pull request merged**
