### PR TITLE
Add two-fer exercise

### PR DESCRIPTION
**Pull request by BNAndras**
Related to #675

### CODE REVIEW

**Review by cmcaine — APPROVED** [review]
Same as eliuded's eggs. Seems fine. Would be nice to have a brief approaches file explaining how to solve it and naming the concepts (default values/optional arguments and string interpolation) and linking to their docs in the manual.

https://docs.julialang.org/en/v1/manual/functions/#Optional-Arguments
https://docs.julialang.org/en/v1/manual/strings/#string-interpolation

**Comment by BNAndras** [comment]
Sure, I'd add a string concatenation approach for completeness, highlighting that interpolation is often more readable.

**Comment by cmcaine** [comment]
For this and the other exercises, do you want me to merge them as-is or would you like to contribute approaches files first? No rush.

**Comment by BNAndras** [comment]
You can merge them. I’m still planning on getting to them.

**Pull request merged**
