### PR TITLE
Fix some writing issues

### PR DESCRIPTION
**Pull request by detinsley1s**

### CODE REVIEW

**Review by cmcaine — COMMENTED** [review]
Changes to the text look fine, tho are these changes supposed to go in the problem-specifications repo instead, @SaschaMann ?

**Comment by SaschaMann** [comment]
Yep, it would be best if these changes were made in exercism/problem-specifications. That way every track benefits and we won't have to manually keep the instructions in sync.

**Comment by detinsley1s** [comment]
Hi, I just opened a PR in the repo you requested, @cmcaine . Thank you very much.

**Comment by SaschaMann** [comment]
Thanks!

**Pull request merged**
