### PR TITLE
Shut up GHA bot

### PR DESCRIPTION
**Pull request by SaschaMann**

### CODE REVIEW

**Review by kytrinyx — APPROVED** [review]

**Review by ErikSchierboom — APPROVED** [review]
Happy for this to be merged, but just to be clear: the responsibility to review PRs falls on the maintainers' shoulders

**Comment by SaschaMann** [comment]
> but just to be clear: the responsibility to review PRs falls on the maintainers' shoulders

Yes, I'm aware bringing tracks to launch when there are new people willing to finish them is not considered important anymore.

**Comment by iHiD** [comment]
> Yes, I'm aware bringing tracks to launch when there are new people willing to finish them is not considered important anymore.

We've launched 3 tracks in the last two weeks and will probably be launching 2 more in the next two weeks, for which Erik has done a tone of work. It is important and I'm not sure why you think otherwise.

However, it's also important that when asking people to contribute to tracks, those tracks have maintainers who will review PRs. Otherwise people are doing work that will never get merged. To ensure that doesn't happen - as in many tracks maintainers actively didn't want to review PRs - we have the GHA. By removing the GHA, you're expressing a willingness to take on the maintenance work of reviewing PRs. That's a responsible and sensible thing to ensure is understood.

**Comment by SaschaMann** [comment]
> It is important and I'm not sure why you think otherwise.

Because I mentioned I'm open to review PRs and help with Julia-specific things but can't help with questions about the purpose of documents or general git/GitHub help. That resulted in "I don't have time for that either." When I asked for this to be disabled (because IIRC it was set via repo topics?) I was told to ask Katrina. Can't exactly say I'm getting the feeling there's any interest in having WIP tracks be picked up again based on those actions.

**Comment by iHiD** [comment]
Erik has one-day per week to support ~65 tracks. I'd say on average each week he's interacting with around 20 of those tracks. Naively that's ~15mins he has to spend on each of those track per week. But most weeks there's at least one big job as part of that (e.g. he's written 3 test runners in the last two weeks), which presuming they take a couple of hours each, leaves him with maybe 5-10 mins per track. Taking a look at the thread in the forum and responding is probably his whole 5-10mins of interactions with that track for the week, and something that in general the OSS community is as able to help with as Erik is, so he probably doesn't see that as a critical job for him, compared to other jobs where he's the only person in a position to do things.

I think you're conflating "interest in WIP tracks" with the reality of Erik's time.

**Pull request merged**
